Rails-Prueba-TLCert/config/routes.rb
Rails.application.routes.draw do
  resources :countries
  devise_for :users
  
  root 'home#index'

  get '/contacto', to: "home#contact"
  get '/terminos-y-condiciones', to: "home#tyc"
  post 'contact_save', to: 'home#contact_save'

  post 'import_materiales', to: 'home#csv_materials'
  post 'import_ciudades', to: 'home#csv_city'

  get '/mantenimiento', to: 'maintenance#new'
  post '/mantenimiento/new', to: 'maintenance#create'

  get '/post-servicio', to: 'post_service#new'
  post '/post-servicio/new', to: 'post_service#create'

  get '/equipo', to: 'equipement#new'
  post '/equipo/new', to: 'equipement#create'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

Rails-Prueba-TLCert/app/models/city.rb
class City < ApplicationRecord
end

Rails-Prueba-TLCert/app/models/contact.rb
class Contact < ApplicationRecord
end

Rails-Prueba-TLCert/app/models/country.rb
class Country < ApplicationRecord
end

Rails-Prueba-TLCert/app/models/detail_material.rb
class DetailMaterial < ApplicationRecord
    belongs_to :material
    belongs_to :maintenance
end

Rails-Prueba-TLCert/app/models/equipement.rb
class Equipement < ApplicationRecord
    has_one_attached :image
end

Rails-Prueba-TLCert/app/models/maintenance.rb
class Maintenance < ApplicationRecord

    enum :type, [:preventivo, :correctivo]
    enum :status, [:aceptado, :en_curso, :finalizado]

    has_many :detail_material

end

Rails-Prueba-TLCert/app/models/material.rb
class Material < ApplicationRecord
    
end

Rails-Prueba-TLCert/app/models/post_service.rb
class PostService < ApplicationRecord
    belongs_to :maintenance
    has_one_attached :evidence
end

Rails-Prueba-TLCert/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  enum :role, [:admin, :regular, :operador]

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

Rails-Prueba-TLCert/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Rails-Prueba-TLCert/app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: %i[ show edit update destroy ]

  # GET /countries or /countries.json
  def index
    @countries = Country.all
  end

  # GET /countries/1 or /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries or /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to country_url(@country), notice: "Country was successfully created." }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1 or /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to country_url(@country), notice: "Country was successfully updated." }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1 or /countries/1.json
  def destroy
    @country.destroy

    respond_to do |format|
      format.html { redirect_to countries_url, notice: "Country was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def country_params
      params.fetch(:country, {})
    end
end

Rails-Prueba-TLCert/app/controllers/equipement_controller.rb
class EquipementController < ApplicationController

    def new
        @equipement = Equipement.new
    end

    def create
        @equipement = Equipement.new(equipement_params)
        respond_to do |format|
            if @equipement.save
                format.html { redirect_to root_path, notice: "El equipamiento ha sido creado exitosamente." }
            else
                format.html { render :roo, status: :unprocessable_entity }
            end
        end
    end

    private 

    def equipement_params
        params.require(:equipement).permit(:type, :name, :description, :image)
    end

end

Rails-Prueba-TLCert/app/controllers/home_controller.rb
require 'csv'

class HomeController < ApplicationController

    # metodos base

    def index
        if current_user.present?
            
        end
    end

    def contact
    end

    def tyc
    end

    # carga de csv's

    def csv_city
        file = params[:city][:file] # Asegúrate de que el atributo `name` coincida con el formulario
        city_save(file)
        redirect_to root_path, notice: "Ciudades cargadas correctamente"
      end
      
      def csv_materials
        file = params[:material][:file] # Asegúrate de que el atributo `name` coincida con el formulario
        
        material_save(file)
        redirect_to root_path, notice: "Materiales cargados correctamente"
      end

    def contact_save
        @contact = Contact.new(contact_params)

        if @contact.save
            redirect_to root_path, notice: "Gracias por tu mensaje de contacto"
        else
            return redirect_to contacto_path
        end

    end

    private

    def city_save(file)
        csv_city = File.read(file.path, encoding: "ISO-8859-1")
        csv = CSV.parse(csv_city, headers: true, col_sep: ',')
        csv.each do |row|
            data_hash = {
                name: row["name"]
            }
            City.create(data_hash)
        end
    end

    def material_save(file)
        csv_material = File.read(file.path, encoding: "ISO-8859-1")
        csv = CSV.parse(csv_material, headers: true, col_sep: ',')
        csv.each do |row|
            data_hash = {
                name: row["name"]
            }
            Material.create(data_hash)
        end
    end

    def contact_params
        params.require(:contact).permit(:name, :email, :number, :consulta)
    end

end

Rails-Prueba-TLCert/app/controllers/maintenance_controller.rb
class MaintenanceController < ApplicationController

    def new
        @maintenance = Maintenance.new
        @materials = Material.all
    end

    def create
        @maintenance = Maintenance.new(maintenance_params)
        respond_to do |format|
            if @maintenance.save
                format.html { redirect_to root_path, notice: "El mantenimiento ha sido creado exitosamente." }
            else
                format.html { render :roo, status: :unprocessable_entity }
            end
        end
    end

    private 
    def maintenance_params
        params.require(:maintenance).permit(:type, :status, :equipements_id, :city_id)
    end
end

Rails-Prueba-TLCert/app/controllers/post_service_controller.rb
class PostServiceController < ApplicationController

    def new
        @maintenances = Maintenance.all
        @postservice = PostService.new
    end

    def create
        @postservice = PostService.new(post_service_params)
        respond_to do |format|
            if @postservice.save
                format.html { redirect_to root_path, notice: "El post-servicio ha sido creado exitosamente." }
            else
                format.html { render :roo, status: :unprocessable_entity }
            end
        end
    end

    private 
    def post_service_params
        params.require(:post_service).permit(:evidence, :maintenance_id)
    end
end

Rails-Prueba-TLCert/app/helpers/application_helper.rb
module ApplicationHelper
end

Rails-Prueba-TLCert/app/helpers/countries_helper.rb
module CountriesHelper
end

Rails-Prueba-TLCert/app/helpers/home_helper.rb
module HomeHelper
end

Rails-Prueba-TLCert/app/views/equipement/new.html.erb
<% content_for :head do %>
  <title>Nuevo equipamiento</title>
<% end %>

<body>
    
    <%= render "shared/navbar" %>
    <div class="container">
        <%= form_for :equipement, url: equipo_new_path, method: :post do |f| %>

            <div class="row py-3">
                <div class="col-12">
                    <h2 class="text-center">Crea un nuevo equipo</h2>
                </div>
            </div>
            
            <div class="row">
                <div class="col-12"><%= flash.notice %></div>
            </div>

            <div class="row py-3">
                <div class="col-12">
                    <div class="form-floating">
                        <select class="form-select" id="floatingSelect" aria-label="Floating label select example" name="equipement[type_equipement]">
                            <option selected>Selecciona</option>
                            <option value="1">Aire acondicionado</option>
                            <option value="2">Calentador</option>
                        </select>
                        <label for="floatingSelect">Elija el tipo de equipo</label>
                    </div>

                </div>
            </div>
            <div class="row py-3">
                <div class="col-12">
                    <%= f.label :name, "Nombre" %>
                    <%= f.text_field :name, class: "form-control", required: true %>
                </div>
            </div>
            <div class="row py-3">
                <div class="col-12">
                    <%= f.label :description, "Descripción" %>
                    <%= f.text_field :description, class: "form-control", required: true %>
                </div>
            </div>
            <div class="row py-3">
                <div class="col-12">
                    <label for="image">Imagen</label>
                    <%= f.file_field :image, class: "form-control" %>
                </div>
            </div>

            <div class="row py-3">
                <%= f.submit "Crea el equipo", class: "btn btn-success w-100" %>
            </div>

        <% end %>
    </div>
    <%= render "shared/footer" %>

</body>    
    

Rails-Prueba-TLCert/app/views/home/contact.html.erb
<% content_for :head do %>
  <title>Contacto - FullClima</title>
<% end %>

<body>
    <%= render "shared/navbar" %>

    <div class="container">
      <div class="row py-5">
        <div class="col-12">
          <h2 class="text-center">Formulario de contacto</h2>
        </div>
      </div>
      
      <%= form_for :contact, url: contact_save_path, method: :post do |f| %>

        <div class="row py-3">
          <%= f.label :name, "Nombre" %>
          <%= f.text_field :name, class: "form-control", required: true %>
        </div>
        <div class="row py-3">
          <%= f.label :email, "Email" %>
          <%= f.text_field :email, class: "form-control", required: true %>
        </div>
        <div class="row py-3">
          <%= f.label :number, "Número telefónico" %>
          <%= f.text_field :number, class: "form-control", type: "number", required: true %>
        </div>
        <div class="row py-3">
          <%= f.label :consulta, "Ingrese su consulta/cotización" %>
          <%= f.text_area :consulta, class: "form-control", required: true %>
        </div>

        <div class="row py-3">
          <%= f.submit "Envíanos tu información", class: "btn btn-success w-100" %>
        </div>

      <% end %>

    </div>

    <%= render "shared/footer" %>
</body>

Rails-Prueba-TLCert/app/views/home/index.html.erb
<% content_for :head do %>
  <title>Home - Prueba</title>
<% end %>

<body>
    <%= render "shared/navbar" %>
    <div class="container">
        <div class="row py-5">
          <div class="col-12">
            <h1 class="text-center">FullClima</h1>
          </div>
        </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-12">
          <p class="text-center">
            <%= flash.notice %>
          </p>
        </div>
      </div>
    </div>

    <% if current_user.present? %>
      <div class="container">
        <div class="row">
          <div class="col-12">
            <h4 class="text-center">Tabla de mantenimientos</h4>
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <table class="table table-striped table-responsive">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Tipo de equipo</th>
                  <th scope="col">Tipo de mantenimiento</th>
                  <th scope="col">Nombre del equipo</th>
                  <th scope="col">Foto</th>
                </tr>
              </thead>
              <tbody>
                <% if @maintenance.present? %>
                  <% @maintenance.each do |maintenance| %>
                    <tr>
                      <td scope="col"></td>
                      <td><%= maintenance.equipement.type %></td>
                      <td><%= maintenance.type %></td>
                      <td><%= maintenance.name %></td>
                      <td><%= maintenance.image %></td>
                    </tr>
                  <% end %>
                <% else %>
                <tr>
                  No hay registros para mostrar en la tabla...
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
        <div class="row py-5">
          <div class="col-6">
            <button type="button" class="btn btn-primary w-100" data-bs-toggle="modal" data-bs-target="#ciudadModal">
              Sube el CSV de las ciudades
            </button>
          </div>
          <div class="col-6">
            <button type="button" class="btn btn-primary w-100" data-bs-toggle="modal" data-bs-target="#materialModal">
              Sube el CSV de los materiales
            </button>
          </div>
        </div>
      </div>

      <!-- modal de ciudades -->

      <div class="modal fade" id="ciudadModal" tabindex="-1" aria-labelledby="ciudadModalContent" aria-hidden="true">
        <div class="modal-dialog modal-lg">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="ciudadModalContent">Ciudad</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <%= form_for :city, url: import_ciudades_path, method: :post do |f| %>
            <div class="modal-body">
              <label for="file">CSV Ciudades</label>
              <%= f.file_field :file, class: "form-control" %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <%= f.submit "Importar ciudades", class: "btn btn-primary" %>
            </div>
            <% end %>
          </div>
        </div>
      </div>

      <!-- modal de materiales -->

      <div class="modal fade" id="materialModal" tabindex="-1" aria-labelledby="materialModalContent" aria-hidden="true">
        <div class="modal-dialog modal-lg">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="materialModalContent">Materiales</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <%= form_for :material, url: import_materiales_path, method: :post do |f| %>
            <div class="modal-body">
              <label for="file">CSV Materiales</label>
              <%= f.file_field :file, class: "form-control" %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <%= f.submit "Importar materiales", class: "btn btn-primary" %>
            </div>
            <% end %>
          </div>
        </div>
      </div>



    <% else %>
      <div class="container-fluid">
        <%= render "shared/home_not_logged" %>
      </div>
    <% end %>

    <%= render "shared/footer" %>
</body>

Rails-Prueba-TLCert/app/views/home/tyc.html.erb
<% content_for :head do %>
  <title>Términos y condiciones - FullClima</title>
<% end %>

<body>
    <%= render "shared/navbar" %>
    <div class="container">
        <div class="row py-5">
            <div class="col-12">
                <h2 class="text-center">Política de Términos y Condiciones</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <p class="text-center">
                    Bienvenido a FullClima. Estos términos y condiciones describen las reglas 
                    y regulaciones para el uso del sitio web FullClima.
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <h5 class="text-center py-5">FullClima se encuentra en Calle falsa #123</h5>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <p>
                    Al acceder a este sitio web, asumimos que aceptas estos términos y condiciones en su totalidad. 
                    No continúes usando el sitio web FullClima si no aceptas todos los términos y condiciones establecidos en esta página.
                </p>
                <p>
                    La siguiente terminología se aplica a estos Términos y Condiciones, Declaración de Privacidad y 
                    Aviso legal y cualquiera o todos los Acuerdos: el Cliente, Usted y Su se refieren a usted, la 
                    persona que accede a este sitio web y acepta los términos y condiciones de la Compañía. La Compañía,
                    Nosotros mismos, Nosotros y Nuestro, se refiere a nuestra Compañía. Parte, Partes o Nosotros, se refiere 
                    en conjunto al Cliente y a nosotros mismos, o al Cliente o a nosotros mismos.
                </p>
                <p>
                    Todos los términos se refieren a la oferta, aceptación y consideración del pago necesario para efectuar 
                    el proceso de nuestra asistencia al Cliente de la manera más adecuada, ya sea mediante reuniones formales 
                    de una duración fija, o por cualquier otro medio, con el propósito expreso de conocer las necesidades del 
                    Cliente con respecto a la provisión de los servicios/productos declarados de la Compañía, de acuerdo con y 
                    sujeto a la ley vigente de Calle falsa #123.</p>
                <p>
                    Cualquier uso de la terminología anterior u otras palabras en singular, plural, mayúsculas y/o, él/ella 
                    o ellos, se consideran intercambiables y, por lo tanto, se refieren a lo mismo.
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <h6>Cookies</h6>
                <p>Empleamos el uso de cookies. Al utilizar el sitio web de FullClima, usted acepta el uso de cookies 
                    de acuerdo con la política de privacidad de FullClima. La mayoría de los modernos sitios web 
                    interactivos de hoy en día usan cookies para permitirnos recuperar los detalles del usuario para cada visita.
                </p>
                <p>
                    Las cookies se utilizan en algunas áreas de nuestro sitio para habilitar la funcionalidad de esta área y la 
                    facilidad de uso para las personas que lo visitan. Algunos de nuestros socios afiliados/publicitarios también pueden usar cookies.
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <h6>Licencia</h6>
                <p>
                    A menos que se indique lo contrario, FullClima y/o sus licenciatarios les pertenecen los derechos 
                    de propiedad intelectual de todo el material en FullClima.
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-12 py-5">
                <h6>Aviso legal</h6>
                <p>
                    En la medida máxima permitida por la ley aplicable, excluimos todas las representaciones, garantías y condiciones relacionadas 
                    con nuestro sitio web y el uso de este sitio web (incluyendo, sin limitación, cualquier garantía implícita por la ley con respecto 
                    a la calidad satisfactoria, idoneidad para el propósito y/o el uso de cuidado y habilidad razonables).
                </p>

            </div>
        </div>

    </div>
    <%= render "shared/footer" %>
</body>

Rails-Prueba-TLCert/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es-CL">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
    <%= favicon_link_tag 'favicon.png' %>


    <%= yield :head %>
 
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <script src="https://kit.fontawesome.com/178860d74b.js" crossorigin="anonymous"></script>
  </head>

  <%= yield %>
  
</html>

Rails-Prueba-TLCert/app/views/maintenance/new.html.erb
<% content_for :head do %>
  <title>Nuevo mantenimiento</title>
<% end %>

<body>
    
    <%= render "shared/navbar" %>

    <div class="container">
        <%= form_for :maintenance, url: mantenimiento_new_path, method: :post do |f| %>

            <div class="row py-5">
                <div class="col-12">
                    <h2 class="text-center">Crea un nuevo mantenimiento</h2>
                </div>
            </div>

            <div class="row">
                <div class="col-12"><%= flash.notice %></div>
            </div>

            <div class="row py-3">
                <div class="col-12">
                    <div class="form-floating">
                        <select class="form-select" id="floatingSelect" aria-label="Floating label select example">
                            <option selected>Selecciona</option>
                            <option value="1">Preventivo</option>
                            <option value="2">Correctivo</option>
                        </select>
                        <label for="floatingSelect">Elija el tipo de mantenimiento</label>
                    </div>
                </div>
            </div>

            <div class="row py-3">
                <% @materials.each do |material| %>
                    <div class="col-4 py-1">
                        <label class="form-check-label">
                        <input class="form-check-input" type="checkbox" name="selected_materials[]" value="<%= material.id %>">
                        <%= material.name %>
                        </label>
                    </div>
                <% end %>
            </div>

            <div class="row py-5">
                <%= f.submit "Crea el mantenimiento", class: "btn btn-success w-100" %>
            </div>

        <% end %>
    </div>

    <%= render "shared/footer" %>

</body>    
    

Rails-Prueba-TLCert/app/views/post_service/new.html.erb
<% content_for :head do %>
  <title>Post - Servicio</title>
<% end %>

<body>
    
    <%= render "shared/navbar" %>
    <div class="container">
        <%= form_for :post_service, url: post_servicio_new_path, method: :post do |f| %>

            <div class="row py-5">
                <div class="col-12">
                    <h2 class="text-center">Crea un nuevo post-servicio</h2>
                </div>
            </div>

            <div class="row">
                <div class="col-12"><%= flash.notice %></div>
            </div>

            <div class="row py-2">
                <div class="col-12">
                    <div class="form-floating">
                        <select class="form-select" id="floatingSelect" aria-label="Floating label select example">
                            <option selected>Selecciona</option>
                            <option value="1">Preventivo</option>
                            <option value="2">Correctivo</option>
                        </select>
                        <label for="floatingSelect">Elija el estado del post-servicio</label>
                    </div>
                </div>
            </div>
            <div class="row py-2">
                <div class="col-12">
                    <div class="form-floating">
                        <select class="form-select" id="floatingSelect" aria-label="Floating label select example">
                            <option selected>Selecciona</option>
                            <% @maintenances.each do |maintenance| %>
                                <option value="<%= maintenance.id %>"><%= maintenance.id %></option>
                            <% end %>   
                        </select>
                        <label for="floatingSelect">Elija el mantenimiento finalizado</label>
                    </div>
                </div>
            </div>

            <div class="row py-5">
                <div class="col-12">
                    <label for="image">Evidencia</label>
                    <%= f.file_field :image, class: "form-control" %>
                </div>
            </div>

            <div class="row py-5">
                <%= f.submit "Crea el equipo", class: "btn btn-success w-100" %>
            </div>

        <% end %>
    </div>
    <%= render "shared/footer" %>

</body>    
    